version: '3'
services:
  db:
    image: mysql
    container_name: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: store_db
    env_file:
      - .env
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/1.sql
      # - ./base.sql:/docker-entrypoint-initdb.d/2.sql
    # ports:
    #   - '3306:3306'
    # expose:
    #   - 3306

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '8085:8080'

  expreeeeee:
    depends_on:
      - db
    container_name: test_express
    image: node:latest
    volumes:
      - ./src/backend:/app
    working_dir: /app
    environment:
      - NODE_ENV=production
    command: ["sh", "-c", "npm install && node index.js"]
    restart: always
    ports:
      - '3000:3000'

  nginx:  
    image: nginx
    container_name: nginx
    links:
      - expreeeeee:expreeeeee
    depends_on:
      - expreeeeee
    ports:
      - '8080:80'
    volumes:
      - ./src/web:/var/www/html
      - ./logs:/var/log/nginx/
      - ./nginx.conf:/etc/nginx/nginx.conf